/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicandpharmacymanagement.view;

import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class ResetView extends javax.swing.JFrame {

    /**
     * Creates new form ResetView
     */
    public ResetView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        oldPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        retypePassword = new javax.swing.JPasswordField();
        retypeVisible = new javax.swing.JCheckBox();
        newVisible = new javax.swing.JCheckBox();
        oldVisible = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("RESET PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 43, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 37, -1));

        userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailActionPerformed(evt);
            }
        });
        getContentPane().add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 81, 128, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 84, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 146, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Old Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 112, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText(" Retype New Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 174, -1, -1));

        resetButton.setBackground(new java.awt.Color(0, 153, 51));
        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 226, -1, -1));

        oldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 109, 128, -1));

        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 143, 128, -1));

        retypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retypePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(retypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 171, 128, -1));

        retypeVisible.setText("show");
        retypeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retypeVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(retypeVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 172, 65, -1));

        newVisible.setText("show");
        newVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(newVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 143, 65, -1));

        oldVisible.setText("show");
        oldVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(oldVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sampleimage.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void retypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retypePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retypePasswordActionPerformed

    private void oldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void retypeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retypeVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retypeVisibleActionPerformed

    private void newVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newVisibleActionPerformed

    private void oldVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldVisibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JCheckBox newVisible;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JCheckBox oldVisible;
    private javax.swing.JButton resetButton;
    private javax.swing.JPasswordField retypePassword;
    private javax.swing.JCheckBox retypeVisible;
    private javax.swing.JTextField userEmail;
    // End of variables declaration//GEN-END:variables

    public JPasswordField getNewPassword() {
        return newPassword;
    }

    public JPasswordField getOldPassword() {
        return oldPassword;
    }

    public JPasswordField getRetypePassword() {
        return retypePassword;
    }

    public JTextField getUserName() {
        return userEmail;
    }

    public JCheckBox getNewVisible() {
        return newVisible;
    }

    public JCheckBox getOldVisible() {
        return oldVisible;
    }

    public JCheckBox getRetypeVisible() {
        return retypeVisible;
    }
    public void showOldPassword(ActionListener listener){
        oldVisible.addActionListener(listener);
    }           
    public void showNewPassword(ActionListener listener){
        newVisible.addActionListener(listener);
    }           
    public void showRetypePassword(ActionListener listener){
        retypeVisible.addActionListener(listener);
    }
        public void reset(ActionListener listener){
        resetButton.addActionListener(listener);
    }
}
